/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PORT_H_RPCGEN
#define _PORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	char *host;
	int start;
	int end;
};
typedef struct input input;

struct output {
	int total;
	int portno[100];
};
typedef struct output output;

typedef input in;

typedef output out;

#define PORT 44
#define PORTVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define getports 1
extern  out * getports_1(in *, CLIENT *);
extern  out * getports_1_svc(in *, struct svc_req *);
extern int port_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getports 1
extern  out * getports_1();
extern  out * getports_1_svc();
extern int port_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);
extern  bool_t xdr_output (XDR *, output*);
extern  bool_t xdr_in (XDR *, in*);
extern  bool_t xdr_out (XDR *, out*);

#else /* K&R C */
extern bool_t xdr_input ();
extern bool_t xdr_output ();
extern bool_t xdr_in ();
extern bool_t xdr_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PORT_H_RPCGEN */
