/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include<stdlib.h>
#include<string.h>


void echo_1(char *host, char* str)
{
	CLIENT *clnt;
	data  *result_1, *input;
	input=(data*)malloc(sizeof(data));
	strcpy(input->buffer, str);
#ifndef	DEBUG
	clnt = clnt_create (host, ECHO, ECHOVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getechoserver_1(input, clnt);
	if (result_1 == (data *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("\n Echo response: %s", result_1->buffer);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	char str[256];
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	while(1)
	{
	printf("\n Enter string to be passed: ");
	scanf("%s", str);
	echo_1 (host, str);
	}
exit (0);
}
