/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/rpc.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>


data * getechoserver_1(data *p1, CLIENT *client)
{
	data *b;
	b=(data*)malloc(sizeof(data));
	strcpy(b->buffer, p1->buffer);
	printf("\n Client Response: %s", b->buffer);
	fflush(stdout);
	return(b);	
}

data * getechoserver_1_svc(data *argp, struct svc_req *rqstp)
{
	CLIENT *client;
	return(getechoserver_1(argp, client));
}
