/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/rpc.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

bool_t getechoserver_1_svc(data *argp, data *result, struct svc_req *rqstp)
{
	bool_t retval =1;
	strcpy(result->buffer, argp->buffer);
	printf("\n Echo response: %s", result->buffer);
	fflush(stdout);
	return retval;
}

int echo_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
