/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "echo.h"
#include<stdlib.h>


void echo_1(char *host, char *str)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	data *result_1, *input;
	input=(data*)malloc(sizeof(data));
	strcpy(input->buffer, str);
	result_1=(data*)malloc(sizeof(data));
	
#ifndef	DEBUG
	clnt = clnt_create (host, ECHO, ECHOVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	 getechoserver_1(input, result_1, clnt);
	printf("\n Server Response: %s", result_1->buffer);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	char str[256];
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	while(1)
	{
		printf("\nEnter string:");
		scanf("%s", str);		
		echo_1 (host, str);
	}
	exit (0);
}
